name: Build macOS .app

on:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Build .app with py2app
        run: |
          echo "Running py2app build..."
          python setup.py py2app || { echo "❌ py2app failed"; exit 1; }
          echo "✅ Build finished"
          echo "=== DIST DIRECTORY TREE ==="
          find dist || true

      - name: Show logs and potential app name
        run: |
          echo "Listing dist contents:"
          ls -lah dist || true
          echo "Looking for .app bundles:"
          find dist -name "*.app" || true

      - name: Zip and Upload if found
        if: success()
        run: |
          APP_PATH=$(find dist -name "*.app" | head -n 1)
          if [ -z "$APP_PATH" ]; then
            echo "::error ::No .app found after build"
            exit 1
          fi
          echo "Found app: $APP_PATH"
          zip -r macos-app.zip "$APP_PATH"
        shell: bash

      - name: Upload .app ZIP
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: macos-app.zip
